[package]
name = "my-tower-timeout"
version = "0.1.0"
edition = "2021"

[dependencies]
pin-project = "1"
tokio = { version = "1", features = ["full"] }
tower = { version = "0.4", features = ["full"] }
